<template>
    <div class="shmetro" v-loading.fullscreen.lock="loading">
        <el-table :data="tableData" border style="position:absolute;top:80px;left:20px;width:281px;z-index:-1;">
            <el-table-column prop="progress" label="步骤" width="140"></el-table-column>
            <el-table-column prop="duration" label="耗时（单位：秒）" width="140"></el-table-column>
        </el-table>
        <el-button @click="reCompute" style="position:absolute;left:110px;top:350px;z-index:1;">重新计算</el-button>
        <div id="container" style="width: 100%;height: 750px;margin: 0 auto;"></div>
    </div>
</template>

<script>
    const $ = require("jquery");

    export default {
        name: "SHMetro",
        data: function () {
            return {
                tableData: [{
                    index: 1,
                    progress: "导入数据到集群",
                    duration: "4.4372"
                }, {
                    index: 2,
                    progress: "数据特征抽取",
                    duration: "38.0346"
                }, {
                    index: 3,
                    progress: "聚类",
                    duration: "1.9658"
                }, {
                    index: 4,
                    progress: "结果处理",
                    duration: "0.0009"
                }, {
                    index: 5,
                    progress: "总计",
                    duration: "44.4390"
                }],
                loading: false
            }
        },
        mounted: function () {
            if (this.$cookie.getCookie("username") == null) {
                this.$router.push("/login");
                return;
            }

            let defaultClusterResult = {
                "name": "上海地铁",
                "children": [{
                    "name": "簇1",
                    "children": [{
                        "name": "松江南站"
                    }, {
                        "name": "醉白池"
                    }, {
                        "name": "中春路"
                    }, {
                        "name": "松江体育中心"
                    }, {
                        "name": "泗泾"
                    }, {
                        "name": "松江新城"
                    }, {
                        "name": "星中路"
                    }, {
                        "name": "松江大学城"
                    }, {
                        "name": "洞泾"
                    }, {
                        "name": "七宝"
                    }, {
                        "name": "佘山"
                    }, {
                        "name": "九亭"
                    }, {
                        "name": "合川路"
                    }]
                }, {
                    "name": "簇2",
                    "children": [{
                        "name": "严御路"
                    }, {
                        "name": "云锦路"
                    }, {
                        "name": "延安西路"
                    }, {
                        "name": "徐家汇"
                    }, {
                        "name": "上海南站"
                    }, {
                        "name": "花木路"
                    }, {
                        "name": "陕西南路"
                    }, {
                        "name": "东安路"
                    }, {
                        "name": "打浦桥"
                    }, {
                        "name": "小南门"
                    }, {
                        "name": "大木桥路"
                    }, {
                        "name": "真北路"
                    }, {
                        "name": "汉中路"
                    }, {
                        "name": "常熟路"
                    }, {
                        "name": "曹杨路"
                    }, {
                        "name": "塘桥"
                    }, {
                        "name": "肇嘉浜路"
                    }, {
                        "name": "漕河泾开发区"
                    }, {
                        "name": "大连路"
                    }, {
                        "name": "七莘路"
                    }, {
                        "name": "南浦大桥"
                    }, {
                        "name": "东兰路"
                    }, {
                        "name": "人民广场"
                    }, {
                        "name": "商城路"
                    }, {
                        "name": "浦东大道"
                    }, {
                        "name": "虹莘路"
                    }, {
                        "name": "马当路"
                    }, {
                        "name": "黄陂南路"
                    }, {
                        "name": "顾戴路"
                    }, {
                        "name": "金沙江路"
                    }, {
                        "name": "桂林路"
                    }, {
                        "name": "金沙江西路"
                    }, {
                        "name": "临平路"
                    }, {
                        "name": "上海火车站"
                    }, {
                        "name": "虹梅路"
                    }, {
                        "name": "上海体育馆"
                    }, {
                        "name": "桂林公园"
                    }, {
                        "name": "大渡河路"
                    }, {
                        "name": "杨树浦路"
                    }, {
                        "name": "海伦路"
                    }, {
                        "name": "鲁班路"
                    }, {
                        "name": "宜山路"
                    }, {
                        "name": "杨高中路"
                    }, {
                        "name": "虹桥路"
                    }, {
                        "name": "嘉善路"
                    }, {
                        "name": "上海体育场"
                    }, {
                        "name": "浦电路"
                    }, {
                        "name": "蓝村路"
                    }, {
                        "name": "漕宝路"
                    }, {
                        "name": "虹漕路"
                    }]
                }, {
                    "name": "簇3",
                    "children": [{
                        "name": "临沂新村"
                    }, {
                        "name": "滴水湖"
                    }, {
                        "name": "博兴路"
                    }, {
                        "name": "凌空路"
                    }, {
                        "name": "航头东"
                    }, {
                        "name": "广兰路"
                    }, {
                        "name": "华夏西路"
                    }, {
                        "name": "外高桥保税区北站"
                    }, {
                        "name": "外高桥保税区南站"
                    }, {
                        "name": "野生动物园"
                    }, {
                        "name": "洲海路"
                    }, {
                        "name": "唐镇"
                    }, {
                        "name": "金桥路"
                    }, {
                        "name": "上南路"
                    }, {
                        "name": "北洋泾路"
                    }, {
                        "name": "创新中路"
                    }, {
                        "name": "五洲大道"
                    }, {
                        "name": "灵岩南路"
                    }, {
                        "name": "源深体育中心"
                    }, {
                        "name": "民生路"
                    }, {
                        "name": "周浦东"
                    }, {
                        "name": "川沙"
                    }, {
                        "name": "云山路"
                    }, {
                        "name": "鹤沙航城"
                    }, {
                        "name": "德平路"
                    }, {
                        "name": "远东大道"
                    }, {
                        "name": "临港大道"
                    }, {
                        "name": "五莲路"
                    }, {
                        "name": "惠南"
                    }, {
                        "name": "华夏中路"
                    }, {
                        "name": "高青路"
                    }, {
                        "name": "上海儿童医学中心"
                    }, {
                        "name": "锦绣路"
                    }, {
                        "name": "惠南东"
                    }, {
                        "name": "华夏东路"
                    }, {
                        "name": "书院"
                    }, {
                        "name": "港城路"
                    }, {
                        "name": "航津路"
                    }, {
                        "name": "高科西路"
                    }, {
                        "name": "东明路"
                    }, {
                        "name": "世纪公园"
                    }, {
                        "name": "龙阳路"
                    }, {
                        "name": "新场"
                    }, {
                        "name": "东靖路"
                    }]
                }, {
                    "name": "簇4",
                    "children": [{
                        "name": "芳华路"
                    }, {
                        "name": "刘行"
                    }, {
                        "name": "长寿路"
                    }, {
                        "name": "祁华路"
                    }, {
                        "name": "美兰湖"
                    }, {
                        "name": "镇坪路"
                    }, {
                        "name": "祁连山南路"
                    }, {
                        "name": "上海大学"
                    }, {
                        "name": "上大路"
                    }, {
                        "name": "大华三路"
                    }, {
                        "name": "场中路"
                    }, {
                        "name": "潘广路"
                    }, {
                        "name": "杨高南路"
                    }, {
                        "name": "武宁路"
                    }, {
                        "name": "长清路"
                    }, {
                        "name": "罗南新村"
                    }, {
                        "name": "顾村公园"
                    }, {
                        "name": "大场镇"
                    }, {
                        "name": "龙华中路"
                    }, {
                        "name": "云台路"
                    }, {
                        "name": "昌平路"
                    }, {
                        "name": "新村路"
                    }, {
                        "name": "南陈路"
                    }, {
                        "name": "岚皋路"
                    }, {
                        "name": "金运路"
                    }, {
                        "name": "行知路"
                    }, {
                        "name": "丰庄"
                    }, {
                        "name": "后滩"
                    }]
                }, {
                    "name": "簇5",
                    "children": [{
                        "name": "国权路"
                    }, {
                        "name": "同济大学"
                    }, {
                        "name": "天潼路"
                    }, {
                        "name": "航中路"
                    }, {
                        "name": "新江湾城"
                    }, {
                        "name": "豫园"
                    }, {
                        "name": "虹桥1号航站楼"
                    }, {
                        "name": "江湾体育场"
                    }, {
                        "name": "四川北路"
                    }, {
                        "name": "交通大学"
                    }, {
                        "name": "新天地"
                    }, {
                        "name": "上海动物园"
                    }, {
                        "name": "五角场"
                    }, {
                        "name": "宋园路"
                    }, {
                        "name": "上海图书馆"
                    }, {
                        "name": "伊犁路"
                    }, {
                        "name": "三门路"
                    }, {
                        "name": "水城路"
                    }, {
                        "name": "邮电新村"
                    }, {
                        "name": "殷高东路"
                    }, {
                        "name": "龙柏新村"
                    }, {
                        "name": "龙溪路"
                    }, {
                        "name": "紫藤路"
                    }]
                }, {
                    "name": "簇6",
                    "children": [{
                        "name": "国际客运中心"
                    }, {
                        "name": "提篮桥"
                    }, {
                        "name": "隆昌路"
                    }, {
                        "name": "江浦公园"
                    }, {
                        "name": "杨高北路"
                    }, {
                        "name": "申江路"
                    }, {
                        "name": "金海路"
                    }, {
                        "name": "爱国路"
                    }, {
                        "name": "巨峰路"
                    }, {
                        "name": "东陆路"
                    }, {
                        "name": "金京路"
                    }, {
                        "name": "复兴岛"
                    }, {
                        "name": "宁国路"
                    }]
                }, {
                    "name": "簇7",
                    "children": [{
                        "name": "龙漕路"
                    }, {
                        "name": "淞发路"
                    }, {
                        "name": "张华浜"
                    }, {
                        "name": "赤峰路"
                    }, {
                        "name": "石龙路"
                    }, {
                        "name": "东宝兴路"
                    }, {
                        "name": "宝杨路"
                    }, {
                        "name": "殷高西路"
                    }, {
                        "name": "水产路"
                    }, {
                        "name": "长江南路"
                    }, {
                        "name": "中潭路"
                    }, {
                        "name": "淞滨路"
                    }, {
                        "name": "大柏树"
                    }, {
                        "name": "宝山路"
                    }, {
                        "name": "漕溪路"
                    }, {
                        "name": "友谊路"
                    }, {
                        "name": "江湾镇"
                    }, {
                        "name": "江杨北路"
                    }, {
                        "name": "铁力路"
                    }]
                }, {
                    "name": "簇8",
                    "children": [{
                        "name": "武威路"
                    }, {
                        "name": "浦三路"
                    }, {
                        "name": "上海游泳馆"
                    }, {
                        "name": "上海西站"
                    }, {
                        "name": "光明路"
                    }, {
                        "name": "上海赛车场"
                    }, {
                        "name": "御桥"
                    }, {
                        "name": "罗山路"
                    }, {
                        "name": "龙华"
                    }, {
                        "name": "东方体育中心"
                    }, {
                        "name": "嘉定北"
                    }, {
                        "name": "李子园"
                    }, {
                        "name": "安亭"
                    }, {
                        "name": "枫桥路"
                    }, {
                        "name": "嘉定新城"
                    }, {
                        "name": "真如"
                    }, {
                        "name": "龙耀路"
                    }, {
                        "name": "兆丰路"
                    }, {
                        "name": "南翔"
                    }, {
                        "name": "三林"
                    }, {
                        "name": "祁连山路"
                    }, {
                        "name": "昌吉东路"
                    }, {
                        "name": "嘉定西"
                    }, {
                        "name": "上海汽车城"
                    }, {
                        "name": "桃浦新村"
                    }, {
                        "name": "马陆"
                    }, {
                        "name": "花桥"
                    }, {
                        "name": "白银路"
                    }, {
                        "name": "三林东"
                    }, {
                        "name": "隆德路"
                    }]
                }, {
                    "name": "簇9",
                    "children": [{
                        "name": "耀华路"
                    }, {
                        "name": "西藏北路"
                    }, {
                        "name": "沈杜公路"
                    }, {
                        "name": "陆家浜路"
                    }, {
                        "name": "虹口足球场"
                    }, {
                        "name": "江月路"
                    }, {
                        "name": "曲阜路"
                    }, {
                        "name": "凌兆新村"
                    }, {
                        "name": "中兴路"
                    }, {
                        "name": "鞍山新村"
                    }, {
                        "name": "江浦路"
                    }, {
                        "name": "嫩江路"
                    }, {
                        "name": "老西门"
                    }, {
                        "name": "大世界"
                    }, {
                        "name": "联航路"
                    }, {
                        "name": "浦江镇"
                    }, {
                        "name": "芦恒路"
                    }, {
                        "name": "黄兴路"
                    }, {
                        "name": "黄兴公园"
                    }, {
                        "name": "市光路"
                    }, {
                        "name": "翔殷路"
                    }, {
                        "name": "杨思"
                    }, {
                        "name": "四平路"
                    }, {
                        "name": "中华艺术宫"
                    }, {
                        "name": "曲阳路"
                    }, {
                        "name": "延吉中路"
                    }, {
                        "name": "西藏南路"
                    }, {
                        "name": "成山路"
                    }]
                }, {
                    "name": "簇10",
                    "children": [{
                        "name": "汶水路"
                    }, {
                        "name": "共富新村"
                    }, {
                        "name": "彭浦新村"
                    }, {
                        "name": "上海马戏城"
                    }, {
                        "name": "富锦路"
                    }, {
                        "name": "呼兰路"
                    }, {
                        "name": "通河新村"
                    }, {
                        "name": "中山北路"
                    }, {
                        "name": "共康路"
                    }, {
                        "name": "新闸路"
                    }, {
                        "name": "延长路"
                    }, {
                        "name": "友谊西路"
                    }, {
                        "name": "宝安公路"
                    }]
                }, {
                    "name": "簇11",
                    "children": [{
                        "name": "虹桥2号航站楼"
                    }, {
                        "name": "世纪大道"
                    }, {
                        "name": "张江高科"
                    }, {
                        "name": "威宁路"
                    }, {
                        "name": "静安寺"
                    }, {
                        "name": "中山公园"
                    }, {
                        "name": "海天三路"
                    }, {
                        "name": "上海科技馆"
                    }, {
                        "name": "淞虹路"
                    }, {
                        "name": "娄山关路"
                    }, {
                        "name": "东昌路"
                    }, {
                        "name": "虹桥火车站"
                    }, {
                        "name": "江苏路"
                    }, {
                        "name": "南京西路"
                    }, {
                        "name": "浦东国际机场"
                    }, {
                        "name": "徐泾东"
                    }, {
                        "name": "北新泾"
                    }, {
                        "name": "南京东路"
                    }, {
                        "name": "陆家嘴"
                    }, {
                        "name": "金科路"
                    }]
                }, {
                    "name": "簇12",
                    "children": [{
                        "name": "银都路"
                    }, {
                        "name": "北桥"
                    }, {
                        "name": "文井路"
                    }, {
                        "name": "莘庄"
                    }, {
                        "name": "闵行开发区"
                    }, {
                        "name": "春申路"
                    }, {
                        "name": "莲花路"
                    }, {
                        "name": "华宁路"
                    }, {
                        "name": "衡山路"
                    }, {
                        "name": "金平路"
                    }, {
                        "name": "东川路"
                    }, {
                        "name": "锦江乐园"
                    }, {
                        "name": "颛桥"
                    }, {
                        "name": "外环路"
                    }, {
                        "name": "剑川路"
                    }]
                }]
            };
            this.$echarts.util.each(defaultClusterResult.children, function (datum, index) {
                $.inArray(index, [1, 2, 4, 7, 8, 9, 11]) + 1 && (datum.collapsed = true);
            });
            this.renderingCharts(defaultClusterResult);
        },
        methods: {
            renderingCharts: function (data) {
                let regressionChart = this.$echarts.init(document.getElementById("container"));
                regressionChart.clear();
                let option = {
                    title: {},
                    tooltip: {
                        trigger: 'item',
                        triggerOn: 'mousemove'
                    },
                    series: [{
                        type: 'tree',
                        data: [data],
                        layout: 'radial',
                        symbol: 'emptyCircle',
                        symbolSize: 7,
                        initialTreeDepth: 2,
                        animationDurationUpdate: 750
                    }]
                };
                regressionChart.setOption(option);
            },
            reCompute: function () {
                let d1 = (4 + Math.random() * 2).toFixed(4);
                let d2 = (35 + Math.random() * 5).toFixed(4);
                let d3 = (1 + Math.random() * 2).toFixed(4);
                let d4 = (Math.random() * 1).toFixed(4);
                let total = (parseFloat(d1) + parseFloat(d2) + parseFloat(d3) + parseFloat(d4)).toFixed(4);

                let defaultClusterResult = {
                    "name": "上海地铁",
                    "children": [{
                        "name": "簇1",
                        "children": [{
                            "name": "松江南站"
                        }, {
                            "name": "醉白池"
                        }, {
                            "name": "中春路"
                        }, {
                            "name": "松江体育中心"
                        }, {
                            "name": "泗泾"
                        }, {
                            "name": "松江新城"
                        }, {
                            "name": "星中路"
                        }, {
                            "name": "松江大学城"
                        }, {
                            "name": "洞泾"
                        }, {
                            "name": "七宝"
                        }, {
                            "name": "佘山"
                        }, {
                            "name": "九亭"
                        }, {
                            "name": "合川路"
                        }]
                    }, {
                        "name": "簇2",
                        "children": [{
                            "name": "严御路"
                        }, {
                            "name": "云锦路"
                        }, {
                            "name": "延安西路"
                        }, {
                            "name": "徐家汇"
                        }, {
                            "name": "上海南站"
                        }, {
                            "name": "花木路"
                        }, {
                            "name": "陕西南路"
                        }, {
                            "name": "东安路"
                        }, {
                            "name": "打浦桥"
                        }, {
                            "name": "小南门"
                        }, {
                            "name": "大木桥路"
                        }, {
                            "name": "真北路"
                        }, {
                            "name": "汉中路"
                        }, {
                            "name": "常熟路"
                        }, {
                            "name": "曹杨路"
                        }, {
                            "name": "塘桥"
                        }, {
                            "name": "肇嘉浜路"
                        }, {
                            "name": "漕河泾开发区"
                        }, {
                            "name": "大连路"
                        }, {
                            "name": "七莘路"
                        }, {
                            "name": "南浦大桥"
                        }, {
                            "name": "东兰路"
                        }, {
                            "name": "人民广场"
                        }, {
                            "name": "商城路"
                        }, {
                            "name": "浦东大道"
                        }, {
                            "name": "虹莘路"
                        }, {
                            "name": "马当路"
                        }, {
                            "name": "黄陂南路"
                        }, {
                            "name": "顾戴路"
                        }, {
                            "name": "金沙江路"
                        }, {
                            "name": "桂林路"
                        }, {
                            "name": "金沙江西路"
                        }, {
                            "name": "临平路"
                        }, {
                            "name": "上海火车站"
                        }, {
                            "name": "虹梅路"
                        }, {
                            "name": "上海体育馆"
                        }, {
                            "name": "桂林公园"
                        }, {
                            "name": "大渡河路"
                        }, {
                            "name": "杨树浦路"
                        }, {
                            "name": "海伦路"
                        }, {
                            "name": "鲁班路"
                        }, {
                            "name": "宜山路"
                        }, {
                            "name": "杨高中路"
                        }, {
                            "name": "虹桥路"
                        }, {
                            "name": "嘉善路"
                        }, {
                            "name": "上海体育场"
                        }, {
                            "name": "浦电路"
                        }, {
                            "name": "蓝村路"
                        }, {
                            "name": "漕宝路"
                        }, {
                            "name": "虹漕路"
                        }]
                    }, {
                        "name": "簇3",
                        "children": [{
                            "name": "临沂新村"
                        }, {
                            "name": "滴水湖"
                        }, {
                            "name": "博兴路"
                        }, {
                            "name": "凌空路"
                        }, {
                            "name": "航头东"
                        }, {
                            "name": "广兰路"
                        }, {
                            "name": "华夏西路"
                        }, {
                            "name": "外高桥保税区北站"
                        }, {
                            "name": "外高桥保税区南站"
                        }, {
                            "name": "野生动物园"
                        }, {
                            "name": "洲海路"
                        }, {
                            "name": "唐镇"
                        }, {
                            "name": "金桥路"
                        }, {
                            "name": "上南路"
                        }, {
                            "name": "北洋泾路"
                        }, {
                            "name": "创新中路"
                        }, {
                            "name": "五洲大道"
                        }, {
                            "name": "灵岩南路"
                        }, {
                            "name": "源深体育中心"
                        }, {
                            "name": "民生路"
                        }, {
                            "name": "周浦东"
                        }, {
                            "name": "川沙"
                        }, {
                            "name": "云山路"
                        }, {
                            "name": "鹤沙航城"
                        }, {
                            "name": "德平路"
                        }, {
                            "name": "远东大道"
                        }, {
                            "name": "临港大道"
                        }, {
                            "name": "五莲路"
                        }, {
                            "name": "惠南"
                        }, {
                            "name": "华夏中路"
                        }, {
                            "name": "高青路"
                        }, {
                            "name": "上海儿童医学中心"
                        }, {
                            "name": "锦绣路"
                        }, {
                            "name": "惠南东"
                        }, {
                            "name": "华夏东路"
                        }, {
                            "name": "书院"
                        }, {
                            "name": "港城路"
                        }, {
                            "name": "航津路"
                        }, {
                            "name": "高科西路"
                        }, {
                            "name": "东明路"
                        }, {
                            "name": "世纪公园"
                        }, {
                            "name": "龙阳路"
                        }, {
                            "name": "新场"
                        }, {
                            "name": "东靖路"
                        }]
                    }, {
                        "name": "簇4",
                        "children": [{
                            "name": "芳华路"
                        }, {
                            "name": "刘行"
                        }, {
                            "name": "长寿路"
                        }, {
                            "name": "祁华路"
                        }, {
                            "name": "美兰湖"
                        }, {
                            "name": "镇坪路"
                        }, {
                            "name": "祁连山南路"
                        }, {
                            "name": "上海大学"
                        }, {
                            "name": "上大路"
                        }, {
                            "name": "大华三路"
                        }, {
                            "name": "场中路"
                        }, {
                            "name": "潘广路"
                        }, {
                            "name": "杨高南路"
                        }, {
                            "name": "武宁路"
                        }, {
                            "name": "长清路"
                        }, {
                            "name": "罗南新村"
                        }, {
                            "name": "顾村公园"
                        }, {
                            "name": "大场镇"
                        }, {
                            "name": "龙华中路"
                        }, {
                            "name": "云台路"
                        }, {
                            "name": "昌平路"
                        }, {
                            "name": "新村路"
                        }, {
                            "name": "南陈路"
                        }, {
                            "name": "岚皋路"
                        }, {
                            "name": "金运路"
                        }, {
                            "name": "行知路"
                        }, {
                            "name": "丰庄"
                        }, {
                            "name": "后滩"
                        }]
                    }, {
                        "name": "簇5",
                        "children": [{
                            "name": "国权路"
                        }, {
                            "name": "同济大学"
                        }, {
                            "name": "天潼路"
                        }, {
                            "name": "航中路"
                        }, {
                            "name": "新江湾城"
                        }, {
                            "name": "豫园"
                        }, {
                            "name": "虹桥1号航站楼"
                        }, {
                            "name": "江湾体育场"
                        }, {
                            "name": "四川北路"
                        }, {
                            "name": "交通大学"
                        }, {
                            "name": "新天地"
                        }, {
                            "name": "上海动物园"
                        }, {
                            "name": "五角场"
                        }, {
                            "name": "宋园路"
                        }, {
                            "name": "上海图书馆"
                        }, {
                            "name": "伊犁路"
                        }, {
                            "name": "三门路"
                        }, {
                            "name": "水城路"
                        }, {
                            "name": "邮电新村"
                        }, {
                            "name": "殷高东路"
                        }, {
                            "name": "龙柏新村"
                        }, {
                            "name": "龙溪路"
                        }, {
                            "name": "紫藤路"
                        }]
                    }, {
                        "name": "簇6",
                        "children": [{
                            "name": "国际客运中心"
                        }, {
                            "name": "提篮桥"
                        }, {
                            "name": "隆昌路"
                        }, {
                            "name": "江浦公园"
                        }, {
                            "name": "杨高北路"
                        }, {
                            "name": "申江路"
                        }, {
                            "name": "金海路"
                        }, {
                            "name": "爱国路"
                        }, {
                            "name": "巨峰路"
                        }, {
                            "name": "东陆路"
                        }, {
                            "name": "金京路"
                        }, {
                            "name": "复兴岛"
                        }, {
                            "name": "宁国路"
                        }]
                    }, {
                        "name": "簇7",
                        "children": [{
                            "name": "龙漕路"
                        }, {
                            "name": "淞发路"
                        }, {
                            "name": "张华浜"
                        }, {
                            "name": "赤峰路"
                        }, {
                            "name": "石龙路"
                        }, {
                            "name": "东宝兴路"
                        }, {
                            "name": "宝杨路"
                        }, {
                            "name": "殷高西路"
                        }, {
                            "name": "水产路"
                        }, {
                            "name": "长江南路"
                        }, {
                            "name": "中潭路"
                        }, {
                            "name": "淞滨路"
                        }, {
                            "name": "大柏树"
                        }, {
                            "name": "宝山路"
                        }, {
                            "name": "漕溪路"
                        }, {
                            "name": "友谊路"
                        }, {
                            "name": "江湾镇"
                        }, {
                            "name": "江杨北路"
                        }, {
                            "name": "铁力路"
                        }]
                    }, {
                        "name": "簇8",
                        "children": [{
                            "name": "武威路"
                        }, {
                            "name": "浦三路"
                        }, {
                            "name": "上海游泳馆"
                        }, {
                            "name": "上海西站"
                        }, {
                            "name": "光明路"
                        }, {
                            "name": "上海赛车场"
                        }, {
                            "name": "御桥"
                        }, {
                            "name": "罗山路"
                        }, {
                            "name": "龙华"
                        }, {
                            "name": "东方体育中心"
                        }, {
                            "name": "嘉定北"
                        }, {
                            "name": "李子园"
                        }, {
                            "name": "安亭"
                        }, {
                            "name": "枫桥路"
                        }, {
                            "name": "嘉定新城"
                        }, {
                            "name": "真如"
                        }, {
                            "name": "龙耀路"
                        }, {
                            "name": "兆丰路"
                        }, {
                            "name": "南翔"
                        }, {
                            "name": "三林"
                        }, {
                            "name": "祁连山路"
                        }, {
                            "name": "昌吉东路"
                        }, {
                            "name": "嘉定西"
                        }, {
                            "name": "上海汽车城"
                        }, {
                            "name": "桃浦新村"
                        }, {
                            "name": "马陆"
                        }, {
                            "name": "花桥"
                        }, {
                            "name": "白银路"
                        }, {
                            "name": "三林东"
                        }, {
                            "name": "隆德路"
                        }]
                    }, {
                        "name": "簇9",
                        "children": [{
                            "name": "耀华路"
                        }, {
                            "name": "西藏北路"
                        }, {
                            "name": "沈杜公路"
                        }, {
                            "name": "陆家浜路"
                        }, {
                            "name": "虹口足球场"
                        }, {
                            "name": "江月路"
                        }, {
                            "name": "曲阜路"
                        }, {
                            "name": "凌兆新村"
                        }, {
                            "name": "中兴路"
                        }, {
                            "name": "鞍山新村"
                        }, {
                            "name": "江浦路"
                        }, {
                            "name": "嫩江路"
                        }, {
                            "name": "老西门"
                        }, {
                            "name": "大世界"
                        }, {
                            "name": "联航路"
                        }, {
                            "name": "浦江镇"
                        }, {
                            "name": "芦恒路"
                        }, {
                            "name": "黄兴路"
                        }, {
                            "name": "黄兴公园"
                        }, {
                            "name": "市光路"
                        }, {
                            "name": "翔殷路"
                        }, {
                            "name": "杨思"
                        }, {
                            "name": "四平路"
                        }, {
                            "name": "中华艺术宫"
                        }, {
                            "name": "曲阳路"
                        }, {
                            "name": "延吉中路"
                        }, {
                            "name": "西藏南路"
                        }, {
                            "name": "成山路"
                        }]
                    }, {
                        "name": "簇10",
                        "children": [{
                            "name": "汶水路"
                        }, {
                            "name": "共富新村"
                        }, {
                            "name": "彭浦新村"
                        }, {
                            "name": "上海马戏城"
                        }, {
                            "name": "富锦路"
                        }, {
                            "name": "呼兰路"
                        }, {
                            "name": "通河新村"
                        }, {
                            "name": "中山北路"
                        }, {
                            "name": "共康路"
                        }, {
                            "name": "新闸路"
                        }, {
                            "name": "延长路"
                        }, {
                            "name": "友谊西路"
                        }, {
                            "name": "宝安公路"
                        }]
                    }, {
                        "name": "簇11",
                        "children": [{
                            "name": "虹桥2号航站楼"
                        }, {
                            "name": "世纪大道"
                        }, {
                            "name": "张江高科"
                        }, {
                            "name": "威宁路"
                        }, {
                            "name": "静安寺"
                        }, {
                            "name": "中山公园"
                        }, {
                            "name": "海天三路"
                        }, {
                            "name": "上海科技馆"
                        }, {
                            "name": "淞虹路"
                        }, {
                            "name": "娄山关路"
                        }, {
                            "name": "东昌路"
                        }, {
                            "name": "虹桥火车站"
                        }, {
                            "name": "江苏路"
                        }, {
                            "name": "南京西路"
                        }, {
                            "name": "浦东国际机场"
                        }, {
                            "name": "徐泾东"
                        }, {
                            "name": "北新泾"
                        }, {
                            "name": "南京东路"
                        }, {
                            "name": "陆家嘴"
                        }, {
                            "name": "金科路"
                        }]
                    }, {
                        "name": "簇12",
                        "children": [{
                            "name": "银都路"
                        }, {
                            "name": "北桥"
                        }, {
                            "name": "文井路"
                        }, {
                            "name": "莘庄"
                        }, {
                            "name": "闵行开发区"
                        }, {
                            "name": "春申路"
                        }, {
                            "name": "莲花路"
                        }, {
                            "name": "华宁路"
                        }, {
                            "name": "衡山路"
                        }, {
                            "name": "金平路"
                        }, {
                            "name": "东川路"
                        }, {
                            "name": "锦江乐园"
                        }, {
                            "name": "颛桥"
                        }, {
                            "name": "外环路"
                        }, {
                            "name": "剑川路"
                        }]
                    }]
                };
                this.$echarts.util.each(defaultClusterResult.children, function (datum, index) {
                    $.inArray(index, [1, 2, 4, 7, 8, 9, 11]) + 1 && (datum.collapsed = true);
                });

                // 清空 Echarts
                let regressionChart = this.$echarts.init(document.getElementById("container"));
                regressionChart.clear();
                // 耗时置为空
                for (let i = 0; i < 5; i++) {
                    this.tableData[i].duration = "-";
                }
                this.loading = true;

                console.log(parseInt(total * 1000));
                // 延时后显示耗时和 Echarts
                setTimeout(() => {
                    this.loading = false;

                    this.tableData[0].duration = d1;
                    this.tableData[1].duration = d2;
                    this.tableData[2].duration = d3;
                    this.tableData[3].duration = d4;
                    this.tableData[4].duration = total;

                    this.renderingCharts(defaultClusterResult);
                }, parseInt(total * 1000));


            }
        }
    }
</script>

<style scoped>

</style>